global:
  resolve_timeout: 1m
  slack_api_url: REDACTED


route:
  receiver: 'slack-notifications'


receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#devops'
        send_resolved: true
